server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:mysql://52.37.62.165:3305/accountingdb'
    username: 'root'
    password: 'mysql'
    driver-class-name: 'com.mysql.jdbc.Driver'
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry:8761/eureka}
  instance:
    preferIpAddress: true

# note: this configuration is needed to avoid timeout upon initial request
#   somehow the initial request needs more time and runs in a timeout with the default settings
# https://github.com/Netflix/Hystrix/wiki/configuration#execution.isolation.thread.timeoutInMilliseconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
